# fly.toml app configuration file generated for big-game-squares on 2025-02-06T21:25:02-08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'big-game-squares'
primary_region = 'ord'

[build]
  dockerfile = 'Dockerfile'

[env]
  NODE_ENV = 'production'
  PORT = '3000'
  VITE_API_URL = 'https://big-game-squares-api.fly.dev'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
