# fly.toml app configuration file generated for big-game-squares-api on 2025-02-06T21:13:25-08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'big-game-squares-api'
primary_region = 'ord'

[build]
  dockerfile = 'Dockerfile'

[env]
  NODE_ENV = 'production'
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
